create table tb_categoria (id int  AUTO_INCREMENT, nome varchar(255), primary key (id));
create table tb_cidade (id int  AUTO_INCREMENT, nome varchar(255), estado_id int, primary key (id));
create table tb_cliente (id int  AUTO_INCREMENT, cpf_ou_cnpj varchar(255), email varchar(255) unique, nome varchar(255), senha varchar(255), tipo int, img_path varchar(255), primary key (id));
create table tb_endereco (id int  AUTO_INCREMENT, bairro varchar(255), cep varchar(255), complemento varchar(255), logradouro varchar(255), numero varchar(255), cidade_id int, cliente_id int, primary key (id));
create table tb_estado (id int  AUTO_INCREMENT, nome varchar(255), primary key (id));
create table tb_item_pedido (desconto decimal(10,2), preco decimal(10,2), quantidade int, produto_id int not null, pedido_id int not null, primary key (pedido_id, produto_id));
create table tb_pagamento (pedido_id int not null, estado int, primary key (pedido_id));
create table tb_pagamento_com_boleto (data_pagamento datetime, data_vencimeto datetime, pedido_id int not null, primary key (pedido_id));
create table tb_pagamento_com_cartao (numero_de_parcelas int, pedido_id int not null, primary key (pedido_id));
create table tb_pedido (id int  AUTO_INCREMENT, instante datetime, cliente_id int, endereco_de_entrega_id int, primary key (id));
create table tb_perfis (cliente_id int not null, perfis int);
create table tb_produto (id int  AUTO_INCREMENT, nome varchar(255), preco decimal(10,2), img_path varchar(255), primary key (id));
create table tb_produto_categoria (produto_id int not null, categoria_id int not null);
create table tb_telefones (cliente_id int not null, telefones varchar(255));
alter table tb_cliente add constraint UK_ir2m70agseiyyajtaxq7wsw20 unique (email);
alter table tb_cidade add constraint FKlxge3ne91xrep1oe4cvrjldmm foreign key (estado_id) references tb_estado;
alter table tb_endereco add constraint FKotpdj815kf867dbkfbctglsjj foreign key (cidade_id) references tb_cidade;
alter table tb_endereco add constraint FKtqe8u5ggrtf93dr80hiibdfd foreign key (cliente_id) references tb_cliente;
alter table tb_item_pedido add constraint FKgfmv77km3wt2evaaq2vkiv2oj foreign key (produto_id) references tb_produto;
alter table tb_item_pedido add constraint FK3qvnhpdyxagngbf1t326cvnse foreign key (pedido_id) references tb_pedido;
alter table tb_pagamento add constraint FKjghfnncmma1w9wn5hnpq6nhx2 foreign key (pedido_id) references tb_pedido;
alter table tb_pagamento_com_boleto add constraint FK3soda87ogb9jhvkhlf9rjpkbw foreign key (pedido_id) references tb_pagamento;
alter table tb_pagamento_com_cartao add constraint FKgxkpgslbqw568tww7uebyh0e8 foreign key (pedido_id) references tb_pagamento;
alter table tb_pedido add constraint FKajo6v90obpung9h40lcain479 foreign key (cliente_id) references tb_cliente;
alter table tb_pedido add constraint FKmfmrxaiieg7pbiuii68005j3q foreign key (endereco_de_entrega_id) references tb_endereco;
alter table tb_perfis add constraint FK97tcnswu8d3slr6hufo9k8102 foreign key (cliente_id) references tb_cliente;
alter table tb_produto_categoria add constraint FK3becm1bka4cpmorcubx1fxl02 foreign key (categoria_id) references tb_categoria;
alter table tb_produto_categoria add constraint FK98jyjls8tavr9o4wur6g9780c foreign key (produto_id) references tb_produto;
alter table tb_telefones add constraint FKh4f7y4jy3od7trggb8d25w9p0 foreign key (cliente_id) references tb_cliente;
INSERT INTO tb_categoria (nome) VALUES ('Informática');
INSERT INTO tb_categoria (nome) VALUES ('Eletrônicos');
INSERT INTO tb_categoria (nome) VALUES ('Limpeza');
INSERT INTO tb_categoria (nome) VALUES ('Cama, Mesa e Banho');
INSERT INTO tb_categoria (nome) VALUES ('Móveis');
INSERT INTO tb_categoria (nome) VALUES ('Celulares');
INSERT INTO tb_categoria (nome) VALUES ('Moda');
INSERT INTO tb_produto (nome, preco) VALUES ('Computador', 2000.00);
INSERT INTO tb_produto (nome, preco) VALUES ('Máquina de Lavar', 600.00);
INSERT INTO tb_produto (nome, preco) VALUES ('Rádio Portátil', 200.00);
INSERT INTO tb_produto (nome, preco) VALUES ('Mesa de escritório', 300.00);
INSERT INTO tb_produto (nome, preco) VALUES ('Toalha', 50.00);
INSERT INTO tb_produto (nome, preco) VALUES ('Colcha', 200.00);
INSERT INTO tb_produto (nome, preco) VALUES ('TV true color', 1200.00);
INSERT INTO tb_produto (nome, preco) VALUES ('Roçadeira', 800.00);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (1, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (1, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (2, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (3, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (4, 5);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (5, 4);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (6, 4);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (7, 4);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (8, 2);
INSERT INTO tb_estado (nome) VALUES ('Distrito Federal');
INSERT INTO tb_estado (nome) VALUES ('Maranhão');
INSERT INTO tb_cidade (nome, estado_id) VALUES ('Brasília', 1);
INSERT INTO tb_cidade (nome, estado_id) VALUES ('São Luís', 2);
INSERT INTO tb_cliente (cpf_ou_cnpj, email, nome, senha, tipo) VALUES ('19219569094', 'teste.email.service@gmail.com', 'Douglas Silva', '$2a$10$65DVJbhhlhquHnT5eHr06utGLNmkJyIA4mCY68msd2K3ST85dgL3i', 1);
INSERT INTO tb_cliente (cpf_ou_cnpj, email, nome, senha, tipo) VALUES ('39333214097', 'silvadouglas328@gmail.com', 'Teste', '$2a$10$65DVJbhhlhquHnT5eHr06utGLNmkJyIA4mCY68msd2K3ST85dgL3i', 1);
INSERT INTO tb_perfis (cliente_id, perfis) VALUES (1, 1);
INSERT INTO tb_perfis (cliente_id, perfis) VALUES (1, 2);
INSERT INTO tb_perfis (cliente_id, perfis) VALUES (2, 2);
INSERT INTO tb_endereco (bairro, cep, complemento, logradouro, numero, cidade_id, cliente_id) VALUES ('Areinha', '65032542', 'Próximo a Igreja', '3ª Rua Nossa Senhora da Aparecida', '100', 1, 1);
INSERT INTO tb_telefones (cliente_id, telefones) VALUES (1, '98991295331');
INSERT INTO tb_telefones (cliente_id, telefones) VALUES (1, '6181241849');
INSERT INTO tb_pedido (instante, cliente_id, endereco_de_entrega_id) VALUES (now(), 1, 1);
INSERT INTO tb_pagamento (pedido_id, estado) VALUES (1, 1);
INSERT INTO tb_pagamento_com_cartao (numero_de_parcelas, pedido_id) VALUES (5, 1);
INSERT INTO tb_item_pedido (desconto, preco, quantidade, produto_id, pedido_id) VALUES (10.00, 300.00, 2, 1, 1);
